[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mtu-validator-project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
maven = ">=3.9.10,<4"
